# Generated by Django 4.2.6 on 2023-10-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='tabla',
            field=models.CharField(default='', max_length=197),
        ),
    ]
