# Generated by Django 4.2.6 on 2023-10-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_alter_horario_tabla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='tabla',
        ),
        migrations.AddField(
            model_name='horario',
            name='horarioDiurno',
            field=models.CharField(default='[[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0]]', max_length=250),
        ),
        migrations.AddField(
            model_name='horario',
            name='horarioVespertino',
            field=models.CharField(default='[[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0]]', max_length=250),
        ),
    ]
